### PR TITLE
Emscripten doesn't give back newline characters on print. We append one

### LINKED ISSUE #166: Printing newlines to console doesn't work
#### Test program

```c
#include <stdio.h>
#include <kipr/wombat.h>

int main()
{
  printf("Hello\nWorld!");
  return 0;
}
```

#### Expected output
```
Hello
World
```

#### Actual output
```
HelloWorld
```

### PR DESCRIPTION
**Pull request by bmcdorman**
Fixes #166

### CODE REVIEW

File: src/util/StyledText.ts [hunk 1]
```diff
@@ -17,27 +17,47 @@ export namespace StyledText {
...
+  export const text = (params: TextParams, addNewline = false): StyledText => {
     
-    const parts = params.text.split('\n');
-    if (parts.length === 1) {
-      return {
-        type: Type.Text,
-        ...params
-      };
-    }
+    console.log(`Text: "${params.text}"`);
```
Comment (navzam) [inline src/util/StyledText.ts:22]: Remove

**Review by navzam — APPROVED** [review]

**Review by tcorbly — APPROVED** [review]
